CREATE DATABASE exercice;

CREATE TABLE CLIENT (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(50)
);

CREATE TABLE AVIS (
    ID SERIAL PRIMARY KEY,
    TEXTE VARCHAR(255),
    TYPE VARCHAR(10),
    CLIENT_ID INTEGER,
    CONSTRAINT client_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);
